export type Verification = "verified" | "pending" | "flagged" | "stale";
export type BrokerStatus = "verified" | "pending" | "flagged" | "suspended";

// Phase 1 launch cities. Expansion beyond these is demand-driven via city requests.
export const PHASE1_CITIES = [
  "Delhi",
  "Gurugram",
  "Noida",
  "Greater Noida",
  "Ghaziabad",
] as const;

export interface Broker {
  id: string;
  name: string;
  agency: string;
  photo: string;
  verified: BrokerStatus;
  rating: number;
  reviews: number;
  recommend: number;
  accuracy: number;
  responseRate: number;
  responseTime: string;
  cities: string[];
  areas: string[];
  cats: string[];
  exp: number;
  tenure: string;
  policy: string;
  vdate: string;
  complaints: number;
  resolved: number;
  kyc: string;
  businessAddress?: string;
  moderationNote?: string;
}

export interface Listing {
  id: string;
  propId: string;
  title: string;
  city: string;
  locality: string;
  sector: string;
  bhk: number;
  type: string;
  rent: number;
  deposit: number;
  furnishing: string;
  area: number;
  floor: string;
  amenities: string[];
  avail: string;
  brok: string;
  brokDays: number;
  visitFee: number;
  visitFeeRefundable?: boolean;
  otherFee: number;
  otherFeeNote?: string;
  photos: string[];
  photoHashes?: string[];
  brokerId: string;
  hrs: number;
  verification: Verification;
  desc: string;
  views: number;
  enq: number;
  flags?: string[];
  ownerName?: string;
  ownerAuthorized?: boolean;
  ownerRelationship?: string;
  availabilityStatus?: string;
  moderationNote?: string;
  revision?: number;
  sourceDraftId?: string | null;
  sourceRequestId?: string | null;
  createdAt?: string | null;
}

export interface Lead {
  id: string;
  listingId: string;
  brokerId: string;
  userName: string;
  phone: string;
  req: string;
  time: string;
  msg: string;
  status: string;
  date: string;
  visit: string;
  mine: boolean;
  visitAt?: string | null;
  seekerVisited?: boolean;
  brokerVisited?: boolean;
  visitProposedBy?: string | null;
  visitAccepted?: boolean;
  outcome?: string | null;
  ownerId?: string | null;
  createdAt?: string | null;
  firstResponseAt?: string | null;
}

export interface Review {
  brokerId: string;
  user: string;
  rating: number;
  text: string;
  date: string;
  tag: string;
}

export interface Report {
  id: string;
  listingId: string;
  brokerId?: string | null;
  targetType?: "listing" | "broker";
  reason: string;
  details: string;
  reporter: string;
  status: string;
  date: string;
}

export interface LeadMessage {
  id: string;
  leadId: string;
  senderId: string;
  body: string;
  createdAt: string;
}

export interface CityRequest {
  id: string;
  city: string;
  name: string;
  phone: string;
  userType: string;
  note: string;
  status: string;
  date: string;
  ownerId?: string | null;
}

const U = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const IMG = {
  a: U("photo-1522708323590-d24dbb6b0267"),
  b: U("photo-1502672260266-1c1ef2d93688"),
  c: U("photo-1560448204-e02f11c3d0e2"),
  d: U("photo-1493809842364-78817add7ffb"),
  e: U("photo-1560185009-5bf9f2849488"),
  f: U("photo-1600596542815-ffad4c1539a9"),
  g: U("photo-1600585154340-be6161a56a0c"),
  h: U("photo-1600607687939-ce8a6c25118c"),
  i: U("photo-1600566753086-00f18fb6b3ea"),
  j: U("photo-1595526114035-0d45ed16cfbf"),
  k: U("photo-1616486338812-3dadae4b4ace"),
  l: U("photo-1600210492486-724fe5c67fb0"),
};

export const PHOTOS = {
  B1: U("photo-1560250097-0b93528c311a", 200),
  B2: U("photo-1573496359142-b8d87734a5a2", 200),
  B3: U("photo-1507003211169-0a1dd7228f2d", 200),
  B4: U("photo-1472099645785-5658abf4ff4e", 200),
  B5: U("photo-1580489944761-15a19d654956", 200),
  B6: U("photo-1500648767791-00dcc994a43e", 200),
  B7: U("photo-1544005313-94ddf0286df2", 200),
  B8: U("photo-1506794778202-cad84cf45f1d", 200),
  B9: U("photo-1519085360753-af0119f7cbe7", 200),
  B10: U("photo-1583864697784-a0efc8379f70", 200),
  B11: U("photo-1595152772835-219674b2a8a6", 200),
  B12: U("photo-1607990281513-2c110a25bd8c", 200),
};

export const brokers: Broker[] = [
  {
    id: "B1",
    name: "Rajesh Kumar",
    agency: "Raj Properties",
    photo: PHOTOS.B1,
    verified: "verified",
    rating: 4.7,
    reviews: 84,
    recommend: 92,
    accuracy: 89,
    responseRate: 96,
    responseTime: "~1.2h",
    cities: ["Delhi"],
    areas: ["Dwarka", "Uttam Nagar", "Janakpuri"],
    cats: ["Family", "2BHK", "3BHK"],
    exp: 8,
    tenure: "3y on platform",
    policy: "15 days brokerage · No visit fee · No hidden charges",
    vdate: "12 Mar 2024",
    complaints: 2,
    resolved: 2,
    kyc: "Aadhaar + Shop licence verified",
  },
  {
    id: "B2",
    name: "Priya Sharma",
    agency: "Saket Homes",
    photo: PHOTOS.B2,
    verified: "verified",
    rating: 4.9,
    reviews: 132,
    recommend: 96,
    accuracy: 94,
    responseRate: 98,
    responseTime: "~45m",
    cities: ["Delhi"],
    areas: ["Saket", "Hauz Khas", "Greater Kailash"],
    cats: ["Premium", "Family", "1BHK"],
    exp: 6,
    tenure: "2.5y on platform",
    policy: "1 month brokerage · No visit fee",
    vdate: "08 Jul 2024",
    complaints: 1,
    resolved: 1,
    kyc: "Aadhaar + GST verified",
  },
  {
    id: "B3",
    name: "Amit Verma",
    agency: "Laxmi Estates",
    photo: PHOTOS.B3,
    verified: "verified",
    rating: 4.5,
    reviews: 67,
    recommend: 88,
    accuracy: 86,
    responseRate: 91,
    responseTime: "~2h",
    cities: ["Delhi"],
    areas: ["Laxmi Nagar", "Mukherjee Nagar", "Dwarka"],
    cats: ["Student", "Budget", "1BHK"],
    exp: 5,
    tenure: "2y on platform",
    policy: "15 days brokerage · No visit fee",
    vdate: "21 Jan 2025",
    complaints: 3,
    resolved: 3,
    kyc: "PAN + Aadhaar verified",
  },
  {
    id: "B4",
    name: "Sunil Yadav",
    agency: "Rohini Rentals",
    photo: PHOTOS.B4,
    verified: "verified",
    rating: 4.6,
    reviews: 91,
    recommend: 90,
    accuracy: 88,
    responseRate: 93,
    responseTime: "~1.5h",
    cities: ["Delhi"],
    areas: ["Rohini", "Janakpuri", "Pitampura"],
    cats: ["Family", "2BHK"],
    exp: 10,
    tenure: "3.5y on platform",
    policy: "20 days brokerage · ₹0 visit fee",
    vdate: "02 Feb 2024",
    complaints: 2,
    resolved: 2,
    kyc: "Aadhaar + Shop licence verified",
  },
  {
    id: "B5",
    name: "Kavya Malhotra",
    agency: "GK Luxury Living",
    photo: PHOTOS.B5,
    verified: "verified",
    rating: 4.8,
    reviews: 56,
    recommend: 95,
    accuracy: 93,
    responseRate: 97,
    responseTime: "~1h",
    cities: ["Delhi"],
    areas: ["Greater Kailash", "Saket", "Hauz Khas"],
    cats: ["Luxury", "3BHK", "4BHK"],
    exp: 7,
    tenure: "2y on platform",
    policy: "1 month brokerage · Accompanied visits",
    vdate: "15 Sep 2024",
    complaints: 0,
    resolved: 0,
    kyc: "GST + Aadhaar verified",
  },
  {
    id: "B6",
    name: "Imran Khan",
    agency: "Karol Realty",
    photo: PHOTOS.B6,
    verified: "verified",
    rating: 4.4,
    reviews: 73,
    recommend: 86,
    accuracy: 84,
    responseRate: 89,
    responseTime: "~2.4h",
    cities: ["Delhi"],
    areas: ["Karol Bagh", "Dwarka", "Rajinder Nagar"],
    cats: ["Family", "Commercial"],
    exp: 9,
    tenure: "4y on platform",
    policy: "1 month brokerage · No visit fee",
    vdate: "30 May 2023",
    complaints: 4,
    resolved: 3,
    kyc: "Aadhaar verified · agency re-check due",
  },
  {
    id: "B7",
    name: "Neha Gupta",
    agency: "Hauz Khas Homes",
    photo: PHOTOS.B7,
    verified: "pending",
    rating: 0,
    reviews: 0,
    recommend: 0,
    accuracy: 0,
    responseRate: 0,
    responseTime: "—",
    cities: ["Delhi"],
    areas: ["Hauz Khas", "Saket"],
    cats: ["Co-living", "1BHK"],
    exp: 2,
    tenure: "Applied 2 days ago",
    policy: "15 days brokerage · No visit fee",
    vdate: "Pending review",
    complaints: 0,
    resolved: 0,
    kyc: "Aadhaar uploaded · agency proof pending",
  },
  {
    id: "B8",
    name: "QuickDeal Properties",
    agency: "QuickDeal",
    photo: PHOTOS.B8,
    verified: "flagged",
    rating: 3.1,
    reviews: 19,
    recommend: 41,
    accuracy: 52,
    responseRate: 64,
    responseTime: "~8h",
    cities: ["Delhi"],
    areas: ["Dwarka", "Rohini"],
    cats: ["Budget"],
    exp: 1,
    tenure: "4m on platform",
    policy: "Undisclosed — under review",
    vdate: "Suspended 28 Sep 2026",
    complaints: 11,
    resolved: 3,
    kyc: "ID mismatch · advance-fee complaints ×6",
  },
  {
    id: "B9",
    name: "Vikram Singh",
    agency: "GurgaonNest Realty",
    photo: PHOTOS.B9,
    verified: "verified",
    rating: 4.6,
    reviews: 58,
    recommend: 91,
    accuracy: 88,
    responseRate: 94,
    responseTime: "~1.4h",
    cities: ["Gurugram"],
    areas: ["Golf Course Road", "Sohna Road", "Sector 29"],
    cats: ["Family", "2BHK", "3BHK"],
    exp: 7,
    tenure: "1.5y on platform",
    policy: "20 days brokerage · No visit fee",
    vdate: "14 Apr 2025",
    complaints: 1,
    resolved: 1,
    kyc: "Aadhaar + GST verified",
  },
  {
    id: "B10",
    name: "Rohit Tanwar",
    agency: "NoidaNest Homes",
    photo: PHOTOS.B10,
    verified: "verified",
    rating: 4.7,
    reviews: 64,
    recommend: 93,
    accuracy: 90,
    responseRate: 95,
    responseTime: "~1h",
    cities: ["Noida"],
    areas: ["Sector 137", "Sector 62", "Sector 150"],
    cats: ["Family", "2BHK", "3BHK"],
    exp: 6,
    tenure: "1.5y on platform",
    policy: "15 days brokerage · No visit fee",
    vdate: "02 Jun 2025",
    complaints: 1,
    resolved: 1,
    kyc: "Aadhaar + Shop licence verified",
  },
  {
    id: "B11",
    name: "Pooja Chaudhary",
    agency: "Pari Chowk Properties",
    photo: PHOTOS.B11,
    verified: "verified",
    rating: 4.5,
    reviews: 41,
    recommend: 89,
    accuracy: 87,
    responseRate: 92,
    responseTime: "~1.8h",
    cities: ["Greater Noida"],
    areas: ["Pari Chowk", "Alpha I", "Knowledge Park"],
    cats: ["Family", "Budget", "2BHK"],
    exp: 5,
    tenure: "1y on platform",
    policy: "15 days brokerage · No visit fee",
    vdate: "19 Aug 2025",
    complaints: 0,
    resolved: 0,
    kyc: "PAN + Aadhaar verified",
  },
  {
    id: "B12",
    name: "Sandeep Tyagi",
    agency: "Indirapuram Estates",
    photo: PHOTOS.B12,
    verified: "verified",
    rating: 4.6,
    reviews: 52,
    recommend: 90,
    accuracy: 88,
    responseRate: 93,
    responseTime: "~1.5h",
    cities: ["Ghaziabad"],
    areas: ["Indirapuram", "Vaishali", "Raj Nagar"],
    cats: ["Family", "2BHK", "3BHK"],
    exp: 8,
    tenure: "1y on platform",
    policy: "15 days brokerage · No visit fee",
    vdate: "05 Jul 2025",
    complaints: 2,
    resolved: 2,
    kyc: "Aadhaar + Shop licence verified",
  },
];

export const listings: Listing[] = [
  {
    id: "L001",
    city: "Delhi",
    propId: "DL-DWK-004821",
    title: "2 BHK Apartment",
    locality: "Dwarka",
    sector: "Sector 12, Near Metro",
    bhk: 2,
    type: "Apartment",
    rent: 24000,
    deposit: 48000,
    furnishing: "Semi-Furnished",
    area: 1050,
    floor: "3 / 5",
    amenities: [
      "Parking",
      "Lift",
      "Power Backup",
      "Park Facing",
      "24x7 Security",
    ],
    avail: "10 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.a, IMG.b, IMG.h],
    brokerId: "B1",
    hrs: 2,
    verification: "verified",
    desc: "Sunlit park-facing 2 BHK, 5 min from Dwarka Sec-12 metro. Modular kitchen, both rooms with wardrobes, east-facing balconies. Family preferred. Society gate verified.",
    views: 342,
    enq: 18,
  },
  {
    id: "L002",
    city: "Delhi",
    propId: "DL-DWK-004821",
    title: "2 BHK Apartment (Same Property)",
    locality: "Dwarka",
    sector: "Sector 12, Near Metro",
    bhk: 2,
    type: "Apartment",
    rent: 24500,
    deposit: 49000,
    furnishing: "Semi-Furnished",
    area: 1050,
    floor: "3 / 5",
    amenities: ["Parking", "Lift", "Power Backup", "Park Facing"],
    avail: "10 Oct 2026",
    brok: "20 days",
    brokDays: 20,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.a, IMG.b, IMG.h],
    brokerId: "B3",
    hrs: 9,
    verification: "verified",
    desc: "Same verified property via second broker. Compare brokerage before you decide — photos hash-matched 98.2%.",
    views: 187,
    enq: 9,
  },
  {
    id: "L003",
    city: "Delhi",
    propId: "DL-DWK-004821",
    title: "2 BHK Apartment (Same Property)",
    locality: "Dwarka",
    sector: "Sector 12, Near Metro",
    bhk: 2,
    type: "Apartment",
    rent: 25000,
    deposit: 50000,
    furnishing: "Semi-Furnished",
    area: 1050,
    floor: "3 / 5",
    amenities: ["Parking", "Lift", "Park Facing"],
    avail: "12 Oct 2026",
    brok: "1 month",
    brokDays: 30,
    visitFee: 200,
    otherFee: 0,
    photos: [IMG.a, IMG.b, IMG.h],
    brokerId: "B6",
    hrs: 26,
    verification: "verified",
    desc: "Third offering for the same property ID. Visit fee ₹200 adjustable on closure. Choose the broker you trust.",
    views: 98,
    enq: 4,
  },
  {
    id: "L004",
    city: "Delhi",
    propId: "DL-SKT-001102",
    title: "3 BHK Builder Floor",
    locality: "Saket",
    sector: "J-Block, Near Max Hospital",
    bhk: 3,
    type: "Builder Floor",
    rent: 55000,
    deposit: 110000,
    furnishing: "Fully-Furnished",
    area: 1650,
    floor: "2 / 3",
    amenities: [
      "Parking",
      "Lift",
      "AC ×4",
      "Modular Kitchen",
      "Terrace Access",
    ],
    avail: "15 Oct 2026",
    brok: "1 month",
    brokDays: 30,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.f, IMG.i, IMG.k],
    brokerId: "B2",
    hrs: 5,
    verification: "verified",
    desc: "Premium furnished floor for working couples / small family. Italian flooring, power backup, stilt parking. Owner documents with broker.",
    views: 512,
    enq: 31,
  },
  {
    id: "L005",
    city: "Delhi",
    propId: "DL-LXN-002344",
    title: "1 BHK Independent Floor",
    locality: "Laxmi Nagar",
    sector: "Near Vikas Marg, Metro 2 min",
    bhk: 1,
    type: "Independent Floor",
    rent: 13500,
    deposit: 27000,
    furnishing: "Semi-Furnished",
    area: 600,
    floor: "1 / 3",
    amenities: ["Metro Nearby", "Water 24x7", "Separate Entry"],
    avail: "Immediate",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.e, IMG.j, IMG.b],
    brokerId: "B3",
    hrs: 3,
    verification: "verified",
    desc: "Ideal for singles / students. Separate entry, no interference, metro at doorstep. Owner-verified via broker.",
    views: 428,
    enq: 42,
  },
  {
    id: "L006",
    city: "Delhi",
    propId: "DL-RHN-003771",
    title: "2 BHK DDA Flat (Renovated)",
    locality: "Rohini",
    sector: "Sector 7, Pocket B",
    bhk: 2,
    type: "DDA Flat",
    rent: 18500,
    deposit: 37000,
    furnishing: "Semi-Furnished",
    area: 900,
    floor: "2 / 4",
    amenities: ["Parking", "Park Facing", "Water 24x7"],
    avail: "20 Oct 2026",
    brok: "20 days",
    brokDays: 20,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.d, IMG.c, IMG.e],
    brokerId: "B4",
    hrs: 30,
    verification: "verified",
    desc: "Freshly renovated DDA flat, new bath fittings + paint. Gated pocket, family crowd. Broker reconfirmed yesterday.",
    views: 264,
    enq: 16,
  },
  {
    id: "L007",
    city: "Delhi",
    propId: "DL-KRB-009811",
    title: "2 BHK — Bait-price suspect",
    locality: "Karol Bagh",
    sector: "Ajmal Khan Rd (flagged)",
    bhk: 2,
    type: "Apartment",
    rent: 9500,
    deposit: 20000,
    furnishing: "Fully-Furnished",
    area: 1100,
    floor: "—",
    amenities: ["AC", "Furnished"],
    avail: "Immediate",
    brok: "Undisclosed",
    brokDays: 0,
    visitFee: 500,
    otherFee: 1500,
    photos: [IMG.f, IMG.g, IMG.k],
    brokerId: "B8",
    hrs: 190,
    verification: "flagged",
    desc: "⚑ AUTO-FLAG: price 58% below locality median · stock-photo hash match ×4 properties · 6 advance-fee complaints on broker. Under moderation — do not pay token.",
    views: 891,
    enq: 3,
    flags: [
      "Price outlier −58%",
      "Stock images ×4",
      "Advance-fee complaints ×6",
      "Undisclosed brokerage",
    ],
  },
  {
    id: "L008",
    city: "Delhi",
    propId: "DL-GK2-005512",
    title: "3 BHK Luxury Apartment",
    locality: "Greater Kailash",
    sector: "GK-2, M-Block",
    bhk: 3,
    type: "Apartment",
    rent: 68000,
    deposit: 136000,
    furnishing: "Fully-Furnished",
    area: 1900,
    floor: "4 / 6",
    amenities: [
      "Lift",
      "Club Access",
      "Concierge",
      "Covered Parking ×2",
      "Pet Friendly",
    ],
    avail: "01 Nov 2026",
    brok: "1 month",
    brokDays: 30,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.g, IMG.h, IMG.i],
    brokerId: "B5",
    hrs: 12,
    verification: "verified",
    desc: "Designer-furnished GK-2 residence, Miele kitchen, servant room, south Delhi society with club. For CXO / expat families.",
    views: 389,
    enq: 22,
  },
  {
    id: "L009",
    city: "Delhi",
    propId: "DL-MNJ-006203",
    title: "1 BHK Student Studio",
    locality: "Mukherjee Nagar",
    sector: "Near Batra Cinema",
    bhk: 1,
    type: "Studio",
    rent: 11000,
    deposit: 22000,
    furnishing: "Furnished",
    area: 450,
    floor: "3 / 4",
    amenities: ["WiFi Ready", "Tiffin Allowed", "Study Table", "Metro 5 min"],
    avail: "Immediate",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.j, IMG.e, IMG.d],
    brokerId: "B3",
    hrs: 7,
    verification: "verified",
    desc: "Coaching-hub favourite. Quiet floor, study setup, cook allowed. 200+ UPSC aspirants placed by this broker.",
    views: 623,
    enq: 58,
  },
  {
    id: "L010",
    city: "Delhi",
    propId: "DL-HZK-007190",
    title: "2 BHK Barsati + Terrace",
    locality: "Hauz Khas",
    sector: "Near Lake, G-Block",
    bhk: 2,
    type: "Barsati",
    rent: 27000,
    deposit: 54000,
    furnishing: "Semi-Furnished",
    area: 950,
    floor: "3 / 3 + Terrace",
    amenities: ["Private Terrace", "Lake View", "Pet Friendly"],
    avail: "18 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.k, IMG.l, IMG.a],
    brokerId: "B7",
    hrs: 50,
    verification: "pending",
    desc: "Charming barsati with 400 sq.ft terrace overlooking the lake. Broker KYC pending — listing visible after approval.",
    views: 74,
    enq: 2,
  },
  {
    id: "L011",
    city: "Delhi",
    propId: "DL-DWK-004933",
    title: "3 BHK Corner Apartment",
    locality: "Dwarka",
    sector: "Sector 6, Near Market",
    bhk: 3,
    type: "Apartment",
    rent: 34000,
    deposit: 68000,
    furnishing: "Semi-Furnished",
    area: 1400,
    floor: "5 / 8",
    amenities: ["Lift", "Parking", "Club", "Power Backup"],
    avail: "25 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.c, IMG.i, IMG.g],
    brokerId: "B1",
    hrs: 18,
    verification: "verified",
    desc: "Corner 3 BHK with double balcony, society club + pool. Genuine family inventory, owner NOC available.",
    views: 298,
    enq: 14,
  },
  {
    id: "L012",
    city: "Delhi",
    propId: "DL-SKT-001540",
    title: "1 BHK Cozy Floor",
    locality: "Saket",
    sector: "Near Metro Gate 2",
    bhk: 1,
    type: "Independent Floor",
    rent: 18000,
    deposit: 36000,
    furnishing: "Furnished",
    area: 550,
    floor: "Ground",
    amenities: ["Metro 2 min", "Separate Entry", "AC"],
    avail: "Immediate",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.b, IMG.d, IMG.j],
    brokerId: "B2",
    hrs: 4,
    verification: "verified",
    desc: "Walk-to-metro 1 BHK for single professional. Ground floor with private patch. Verified this morning.",
    views: 351,
    enq: 27,
  },
  {
    id: "L013",
    city: "Delhi",
    propId: "DL-JNK-008120",
    title: "2 BHK — Stale, needs reconfirm",
    locality: "Janakpuri",
    sector: "C-Block",
    bhk: 2,
    type: "DDA Flat",
    rent: 21500,
    deposit: 43000,
    furnishing: "Unfurnished",
    area: 950,
    floor: "1 / 4",
    amenities: ["Parking"],
    avail: "—",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.d, IMG.e, IMG.c],
    brokerId: "B4",
    hrs: 200,
    verification: "stale",
    desc: "Last verified 8 days ago. Ranked lower until broker reconfirms. Enquire only if you want us to nudge the broker.",
    views: 120,
    enq: 2,
  },
  {
    id: "L014",
    city: "Delhi",
    propId: "DL-UTM-009001",
    title: "1 RK Budget Room",
    locality: "Uttam Nagar",
    sector: "Near Metro Pillar 654",
    bhk: 1,
    type: "1 RK",
    rent: 9000,
    deposit: 18000,
    furnishing: "Semi-Furnished",
    area: 350,
    floor: "2 / 4",
    amenities: ["Metro Nearby", "Water 24x7"],
    avail: "Immediate",
    brok: "10 days",
    brokDays: 10,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.e, IMG.j, IMG.l],
    brokerId: "B1",
    hrs: 11,
    verification: "verified",
    desc: "Clean budget RK for single worker / student. Lowest brokerage slab on platform.",
    views: 410,
    enq: 35,
  },
  {
    id: "L015",
    city: "Gurugram",
    propId: "GGN-GLF-001201",
    title: "2 BHK Highrise Apartment",
    locality: "Golf Course Road",
    sector: "Sector 42, Near Rapid Metro",
    bhk: 2,
    type: "Apartment",
    rent: 38000,
    deposit: 76000,
    furnishing: "Semi-Furnished",
    area: 1250,
    floor: "9 / 22",
    amenities: ["Club", "Pool", "Power Backup", "Covered Parking"],
    avail: "12 Oct 2026",
    brok: "20 days",
    brokDays: 20,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.f, IMG.h, IMG.c],
    brokerId: "B9",
    hrs: 6,
    verification: "verified",
    desc: "High-floor 2 BHK with golf-course facing balcony, 2 min from Rapid Metro. Gated society with club.",
    views: 287,
    enq: 19,
  },
  {
    id: "L016",
    city: "Gurugram",
    propId: "GGN-SHN-001455",
    title: "3 BHK Builder Floor",
    locality: "Sohna Road",
    sector: "Sector 48, Near Market",
    bhk: 3,
    type: "Builder Floor",
    rent: 32000,
    deposit: 64000,
    furnishing: "Semi-Furnished",
    area: 1550,
    floor: "2 / 3",
    amenities: ["Parking", "Park Facing", "Power Backup"],
    avail: "18 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.d, IMG.g, IMG.i],
    brokerId: "B9",
    hrs: 14,
    verification: "verified",
    desc: "Corner builder floor on green belt, separate drawing-dining, owner NOC available. Family preferred.",
    views: 203,
    enq: 11,
  },
  {
    id: "L017",
    city: "Noida",
    propId: "ND-137-002301",
    title: "2 BHK Riverside Apartment",
    locality: "Sector 137",
    sector: "Near Felix Hospital",
    bhk: 2,
    type: "Apartment",
    rent: 20000,
    deposit: 40000,
    furnishing: "Semi-Furnished",
    area: 1100,
    floor: "7 / 19",
    amenities: ["Club", "Pool", "Yamuna View", "Power Backup"],
    avail: "Immediate",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.c, IMG.a, IMG.k],
    brokerId: "B10",
    hrs: 4,
    verification: "verified",
    desc: "River-facing 2 BHK in high-demand riverside society, metro + expressway connectivity. Verified this week.",
    views: 356,
    enq: 29,
  },
  {
    id: "L018",
    city: "Noida",
    propId: "ND-062-002455",
    title: "3 BHK Park Facing Flat",
    locality: "Sector 62",
    sector: "Near Fortis Hospital",
    bhk: 3,
    type: "Apartment",
    rent: 28000,
    deposit: 56000,
    furnishing: "Semi-Furnished",
    area: 1450,
    floor: "4 / 10",
    amenities: ["Parking", "Lift", "Park Facing", "Power Backup"],
    avail: "22 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.h, IMG.e, IMG.b],
    brokerId: "B10",
    hrs: 9,
    verification: "verified",
    desc: "Central Noida 3 BHK opposite city park, walk to blue line metro. Ideal for working couples.",
    views: 241,
    enq: 15,
  },
  {
    id: "L019",
    city: "Greater Noida",
    propId: "GN-PC-003101",
    title: "2 BHK Society Apartment",
    locality: "Pari Chowk",
    sector: "Alpha I, Near Metro",
    bhk: 2,
    type: "Apartment",
    rent: 15000,
    deposit: 30000,
    furnishing: "Semi-Furnished",
    area: 1050,
    floor: "5 / 14",
    amenities: ["Club", "Pool", "Power Backup", "Kids Play"],
    avail: "Immediate",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.e, IMG.c, IMG.j],
    brokerId: "B11",
    hrs: 5,
    verification: "verified",
    desc: "Bright 2 BHK 5 min from Pari Chowk metro, university belt nearby. Great value for young families.",
    views: 312,
    enq: 26,
  },
  {
    id: "L020",
    city: "Greater Noida",
    propId: "GN-AL-003220",
    title: "1 BHK Budget Apartment",
    locality: "Alpha I",
    sector: "Near LG Chowk",
    bhk: 1,
    type: "Apartment",
    rent: 11000,
    deposit: 22000,
    furnishing: "Furnished",
    area: 620,
    floor: "3 / 12",
    amenities: ["Metro Nearby", "Power Backup"],
    avail: "Immediate",
    brok: "10 days",
    brokDays: 10,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.j, IMG.d, IMG.l],
    brokerId: "B11",
    hrs: 8,
    verification: "verified",
    desc: "Furnished 1 BHK for singles near Knowledge Park colleges. Lowest brokerage slab in Greater Noida.",
    views: 389,
    enq: 33,
  },
  {
    id: "L021",
    city: "Ghaziabad",
    propId: "GZB-IN-004011",
    title: "2 BHK Gated Society Flat",
    locality: "Indirapuram",
    sector: "Ahinsa Khand, Near Mall",
    bhk: 2,
    type: "Apartment",
    rent: 14000,
    deposit: 28000,
    furnishing: "Semi-Furnished",
    area: 1000,
    floor: "6 / 18",
    amenities: ["Club", "Power Backup", "Mall Nearby"],
    avail: "15 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.b, IMG.i, IMG.e],
    brokerId: "B12",
    hrs: 7,
    verification: "verified",
    desc: "Well-kept 2 BHK in Indirapuram's best-connected block, 10 min to Anand Vihar ISBT. Family crowd.",
    views: 276,
    enq: 21,
  },
  {
    id: "L022",
    city: "Ghaziabad",
    propId: "GZB-VA-004132",
    title: "3 BHK Corner Flat",
    locality: "Vaishali",
    sector: "Sector 4, Near Metro",
    bhk: 3,
    type: "Apartment",
    rent: 19000,
    deposit: 38000,
    furnishing: "Semi-Furnished",
    area: 1350,
    floor: "2 / 8",
    amenities: ["Parking", "Lift", "Park Facing"],
    avail: "25 Oct 2026",
    brok: "15 days",
    brokDays: 15,
    visitFee: 0,
    otherFee: 0,
    photos: [IMG.i, IMG.f, IMG.a],
    brokerId: "B12",
    hrs: 16,
    verification: "verified",
    desc: "Corner 3 BHK walk-to-metro in Vaishali, double balcony, society park. Owner documents with broker.",
    views: 198,
    enq: 12,
  },
];

export const leads: Lead[] = [
  {
    id: "LD-2081",
    listingId: "L005",
    brokerId: "B3",
    userName: "Ananya Gupta",
    phone: "98110XXXXX",
    req: "Student / sharing",
    time: "06 Oct, 11:00 AM",
    msg: "Need near metro, budget 14k max. Is it still available?",
    status: "Visit Scheduled",
    date: "2 Oct 2026",
    visit: "06 Oct · 11 AM · Laxmi Nagar",
    mine: true,
  },
  {
    id: "LD-2074",
    listingId: "L001",
    brokerId: "B1",
    userName: "Rohit Malhotra",
    phone: "98990XXXXX",
    req: "Family relocation",
    time: "Evening",
    msg: "Family of 4, need parking + park facing.",
    status: "Contacted",
    date: "1 Oct 2026",
    visit: "—",
    mine: false,
  },
  {
    id: "LD-2071",
    listingId: "L004",
    brokerId: "B2",
    userName: "Sana Sheikh",
    phone: "99580XXXXX",
    req: "Ready in 15 days",
    time: "Weekend",
    msg: "Working couple, need fully furnished.",
    status: "New",
    date: "1 Oct 2026",
    visit: "—",
    mine: false,
  },
  {
    id: "LD-2066",
    listingId: "L009",
    brokerId: "B3",
    userName: "Aditya Rao",
    phone: "98110XXXXX",
    req: "Student",
    time: "Morning",
    msg: "UPSC aspirant, need quiet room.",
    status: "Visited",
    date: "29 Sep 2026",
    visit: "02 Oct · Visited ✓",
    mine: false,
  },
  {
    id: "LD-2060",
    listingId: "L008",
    brokerId: "B5",
    userName: "Meera Iyer",
    phone: "98110XXXXX",
    req: "Family",
    time: "Weekend",
    msg: "Expat family, need pet friendly.",
    status: "Negotiating",
    date: "27 Sep 2026",
    visit: "30 Sep · Visited ✓",
    mine: false,
  },
];

export const reviews: Review[] = [
  {
    brokerId: "B1",
    user: "Rohit M.",
    rating: 5,
    text: "Flat exactly as photos. Broker disclosed 15-day brokerage upfront, zero visit fee. Visit on time.",
    date: "28 Sep 2026",
    tag: "DL-DWK-004821",
  },
  {
    brokerId: "B1",
    user: "Farah K.",
    rating: 4,
    text: "Good communication, one reschedule but informed early. Availability was accurate.",
    date: "20 Sep 2026",
    tag: "DL-DWK-004933",
  },
  {
    brokerId: "B2",
    user: "Sana S.",
    rating: 5,
    text: "Most professional broker in Saket. Documents ready, no pressure for token.",
    date: "25 Sep 2026",
    tag: "DL-SKT-001102",
  },
  {
    brokerId: "B3",
    user: "Aditya R.",
    rating: 5,
    text: "Helped 3 hostels + this studio. Honest about water timings. Highly recommend for students.",
    date: "02 Oct 2026",
    tag: "DL-MNJ-006203",
  },
  {
    brokerId: "B5",
    user: "Meera I.",
    rating: 5,
    text: "White-glove experience for our relocation. Society verification handled.",
    date: "30 Sep 2026",
    tag: "DL-GK2-005512",
  },
];

export const reports: Report[] = [
  {
    id: "RP-331",
    listingId: "L007",
    reason: "Advance / token demanded",
    details: "Asked ₹5,000 token on call before visit.",
    reporter: "Anonymous seeker",
    status: "Open · auto-escalated",
    date: "04 Oct 2026",
  },
  {
    id: "RP-328",
    listingId: "L007",
    reason: "Fake / stock photos",
    details: "Same photos on 4 listings across portals.",
    reporter: "System · hash-match",
    status: "Open",
    date: "03 Oct 2026",
  },
  {
    id: "RP-325",
    listingId: "L013",
    reason: "Already rented but advertised",
    details: "Guard said flat rented last week.",
    reporter: "Verified visitor",
    status: "Nudged broker",
    date: "02 Oct 2026",
  },
];
