import type { Metadata } from "next";
import Link from "next/link";
import PolicyPage from "@/components/policy-page";
import { STALE_AFTER_HRS } from "@/lib/trust";
export const metadata: Metadata = { title: "Broker Agreement — Thikana" };
export default function BrokerAgreementPage() {
  return <PolicyPage title="A clear promise before every visit." audience="BROKER AGREEMENT" intro="Your responsibilities when you apply, advertise a home, receive an enquiry or charge for your service. Read alongside the Terms of use and Privacy Notice." sections={[
    { title: "Representing a broker or agency", body: <p>You confirm you are at least 18, your information is accurate and you are authorised to represent the named agency. Maintain registrations, permissions or licences legally required for your actual activities. Platform verification is not a professional licence or government accreditation. Notify the team when your identity, agency or authority changes.</p> },
    { title: "Private verification and your choices", body: <><p>Provide your own identity and business proof and a current business address. Use masked identity documents. Aadhaar is not the only acceptable identity document: suitable passport, driving-licence or other identity proof can be assessed by a human reviewer. Do not upload full Aadhaar numbers, biometrics, payment credentials or passwords. Manual document review is not a claim of official Aadhaar e-KYC.</p><p>The application separately requests permission to review proof for verification and related fraud/dispute handling. Reviewer access is private. A phone number on file is not OTP-verified; phone OTP remains pending. You can request correction or withdraw verification consent through <Link href="/support/privacy">Privacy & appeals</Link>. If necessary checks can no longer be performed, the team may pause approval or remove the badge and will explain why.</p></> },
    { title: "Authority for every home", body: <p>Obtain the owner’s permission before listing. State whether you are the owner, agent or subagent and give truthful owner/address information to the platform. Keep evidence of authority for review. Do not imply an exclusive appointment you do not have, impersonate a landlord, advertise a nonexistent home or copy another broker’s photos without permission.</p> },
    { title: "Accurate inventory and imagery", body: <p>Publish actual prices, fees, property details and current photos. Identify material photo edits or illustrative renders. Avoid occupants’ faces, identity documents and private belongings. Mark Taken or On Hold homes promptly and reconfirm available homes at least every {STALE_AFTER_HRS / 24} days. Price, fee or photo edits may require re-review. Answer duplicate/address alerts with evidence rather than evading them through changed URLs or new accounts.</p> },
    { title: "Fees before collection", body: <><p>Disclose brokerage calculation, visit fee, refundability and every mandatory additional charge. Explain non-zero additional fees. State who collects each payment, when it is due, the service it covers and the cancellation/refund conditions. Do not demand an undisclosed fee on arrival at a visit.</p><p>Give receipts for payments you collect. Honour written refund terms and stated repayment deadlines, including what happens if you or the landlord cancels. Do not describe an off-platform payment as held or protected by Thikana. This agreement imposes no current platform subscription, lead-credit or escrow charge. Future charges need a separate clear offer and acceptance.</p></> },
    { title: "Protect tenant information", body: <p>Use contact details for the home or service the tenant requested. Limit access to authorised agency staff working on that enquiry. Do not sell leads, forward them to unrelated brokers, add people to marketing groups or repeatedly contact someone who asks you to stop. Explain and protect records you keep outside Thikana. Report accidental disclosure or loss of a device containing tenant information to the platform team promptly.</p> },
    { title: "Visits, outcomes and reviews", body: <p>Reply accurately, agree visit times and notify participants of cancellations. Confirm attendance only when a visit happened and record booked/not-interested outcomes honestly. Do not fabricate confirmations, reward positive ratings or retaliate against complaints. A visit creates no obligation for the tenant to book or leave a favourable review.</p> },
    { title: "Review, restriction and appeal", body: <p>Provide reasonable evidence requested during verification or investigations. Staff may request corrections, restrict inventory, suspend or reinstate an account. Automated alerts are signals for review, not conclusive findings. Recorded reasons and appeals help correct mistakes. Use <Link href="/support/privacy">Privacy & appeals</Link> to challenge a decision. Reviewers with a personal or financial connection must hand the case to another reviewer.</p> },
    { title: "Leaving and recorded acceptance", body: <><p>Leaving does not erase obligations for payments already collected, agreed refunds or lawful dispute evidence. Stop advertising unavailable homes and arrange a responsible handover of existing enquiries. Request closure or deletion through the privacy form.</p><p>New applications require explicit acceptance of this agreement and the Terms of use, plus separate verification consent under the Privacy Notice. The server records policy versions and acceptance times with the application. Existing accounts are not retrospectively marked as having accepted these versions.</p><Link href="/broker/onboard">Apply or update your broker application →</Link></> },
  ]} />;
}
