import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getAssurance, getSessionUser, userRole } from "@/lib/supabase/role";
import PolicyPage from "@/components/policy-page";
export const metadata: Metadata = { title: "Staff policy — Thikana", robots: { index: false, follow: false } };
export default async function AdminPolicyPage() {
  const user = await getSessionUser();
  if (!user) redirect("/auth?next=/admin/policy");
  if (userRole(user) !== "admin") redirect("/dashboard");
  if ((await getAssurance()).current !== "aal2") redirect("/admin/mfa");
  return <PolicyPage title="Review the evidence. Keep the record." audience="INTERNAL STAFF POLICY" intro="Responsibilities for every reviewer with access to broker documents, tenant conversations or moderation decisions." sections={[
    { title: "Named access and confidentiality", body: <p>Use your own staff account and MFA. Do not share credentials or recovery codes. Access only the records needed for an assigned task, close private-document views after use and revoke access promptly when a reviewer leaves or changes role. Never download proof to personal devices or share it through personal email, WhatsApp or public links. Export only for an approved, recorded purpose.</p> },
    { title: "Verification checklist", body: <p>Check identity/business proof is readable, belongs to the applicant and supports the stated agency. Check email confirmation, business address and consistency with the application. Record what was actually checked and the decision date. Phone-on-file is not OTP confirmation: identify pending checks honestly. Missing/expired/inconsistent proof needs a correction request, not an approval. Public proof summaries must not reveal document numbers or private files.</p> },
    { title: "Evidence and proportionate decisions", body: <p>Treat reports and automated fraud alerts as signals, not proven findings. Compare related listings and both parties’ evidence. Ask the reporter or broker for relevant clarification. Record the reason, affected record and outcome of an approval, correction, restriction, suspension, reinstatement or dismissal. Urgent protective action must have a reason and subsequent review. Do not edit ratings or testimonials to favour a broker or manufacture visit confirmations.</p> },
    { title: "Conflicts, appeals and corrections", body: <p>Disclose personal, agency or financial connections and transfer conflicted cases to another reviewer. An appeal should receive an independent review where practical. Explain decisions without exposing another person’s private information. Correct mistakes with an attributed follow-up record; do not erase earlier decisions or silently reopen resolved cases.</p> },
    { title: "Privacy requests and identity checks", body: <><p>Work privacy and account-access requests in the <Link href="/admin/privacy-requests">dedicated queue</Link>, separately from fraud reports. Verify the requester through their signed-in account or proportionate checks before disclosure, correction, closure or deletion. Request only necessary evidence; never ask for passwords, OTPs, full Aadhaar numbers or bank credentials.</p><p>Carry out the underlying authorised action before closing a request. State what changed, any remaining records, the retention reason and any lawful next step. Completing a queue item records a response; it does not itself delete an account. Respond to general grievances within the 24-hour acknowledgement/seven-day resolution targets and apply urgent statutory deadlines where relevant.</p></> },
    { title: "Retention, holds and security incidents", body: <p>At case closure and after three years, review whether complaint evidence, privacy requests, agreement records and audit details are still needed. Remove unnecessary proof after verification ends or an application is rejected/withdrawn unless an appeal, fraud case or lawful hold requires it. Document the reason, scope, reviewer and next review date for a hold. An incident requires prompt containment, preservation of necessary evidence, escalation to the responsible operator and applicable notifications. No indefinite retention merely because a file might be useful later.</p> },
    { title: "Lawful disclosure and operating ownership", body: <p>Route authority requests and legal notices to the responsible operator. Check validity and scope, disclose only what is required and record the decision securely. The operator must appoint a grievance owner, complete public contact/deployment details and arrange actual coverage for requests before launch. Every shift needs clear ownership of unresolved cases and an escalation route.</p> },
    { title: "Staff privacy and accountability", body: <><p>Your staff identity, authentication/MFA records, decisions and relevant security activity may be recorded for access control, auditing and incident handling. These records are restricted to authorised operations/security staff and lawful disclosures. They are not permission for unrelated surveillance. You can request access/correction through the same privacy channel; account removal does not erase appropriately retained decision attribution.</p><Link href="/admin">Return to moderation →</Link></> },
  ]} />;
}
